version: '3.7'

services:
  web:
    image: alexcheng/magento2:latest
    ports:
      - "8081:80"
    volumes:
      - magento-data:/var/www/html
    depends_on:
      - php
      - db
      - redis
      - elasticsearch
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - REDIS_HOST=redis
      - ELASTICSEARCH_HOST=elasticsearch
      - MAGENTO_RUN_MODE=developer
    networks:
      - magento-network

  php:
    image: php:7.4-fpm
    volumes:
      - magento-data:/var/www/html
    networks:
      - magento-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - magento-network

  redis:
    image: redis:latest
    networks:
      - magento-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    networks:
      - magento-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - magento-data:/var/www/html
    depends_on:
      - php
      - web
    networks:
      - magento-network

volumes:
  magento-data:
  db-data:

networks:
  magento-network:
    driver: bridge